---

- name: "Create folder {{ workspace }}"
  file:
    path: "{{ workspace }}"
    recurse: yes
    state: directory
    owner: nginx
    group: nginx
    mode: 0775

- name: Clone {{ repo }} inside {{ workspace }}
  shell: git clone "{{ git_repo }}"
  args:
    chdir:  "{{ workspace }}"

- name: Get workspace basename
  shell: basename {{ git_repo }}
  register: folder_name

- name: Copy repo content inside {{ workspace }}
  shell: cp -r "{{ folder_name.stdout }}"/* .
  args:
    chdir: "{{ workspace }}"

- name: "Change access right folder {{ workspace }}"
  file:
    path: "{{ workspace }}"
    recurse: yes
    state: directory
    owner: nginx
    group: nginx
    mode: 0775

- name: "Remove useless folder"
  file:
    path: "{{ folder_name.stdout }}/*"
    recurse: yes
    state: absent