---
- name: Load composer
  get_url:
    url: https://getcomposer.org/installer
    dest: "/opt/composer-setup.php"
    mode: 0777

- name: Install composer
  shell: php /opt/composer-setup.php --quiet --install-dir=/usr/bin --filename=composer

- name: Remove installer
  file:
    path: /opt/composer-setup.php
    state: absent

- name: Install test
  shell: composer -V
  register: success

- name: Ensure composer is now installer
  assert:
    that:
      - success.rc == 0
    msg: "Error during composer installation"